### ISSUE TITLE
Licence and documentation

### ISSUE THREAD

**Issue by xplicit** [jefffhaynes/BinarySerializer#2] opened 2014-12-31 02:50 UTC
What is licence for using binaryserializer and where can be found documentation?

**Comment by jefffhaynes** [comment] 2015-01-01 20:40
Yes, it's annoying that StructLayout or something similar isn't meant for this.  The only other option is the metadata token, but I'm not convinced that's any more reliable.  I may have to enforce a field attribute.

**Comment by jefffhaynes** [comment] 2015-01-01 23:14
Ok, I'm adding a required FieldOrder attribute in the new version.

On Thu, Jan 1, 2015 at 3:40 PM, Jeff Haynes <feedyurhed@gmail.com> wrote:

> Yes, it's annoying that StructLayout or something similar isn't meant for
> this.  The only other option is the metadata token, but I'm not convinced
> that's any more reliable.  I may have to enforce a field attribute.
>
>
> On Dec 31, 2014, at 4:19 PM, Sergey Zhukov <notifications@github.com>
> wrote:
>
> That's the common practice, when serializer works only with propeties, at
> least the most serializers I know work like that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jefffhaynes/BinarySerializer/issues/2#issuecomment-68469802>
> .
>
>


-- 
If you want to build a ship, don't drum up people together to collect wood
and don't assign them tasks and work, but rather teach them to long for the
endless immensity of the sea.

Antoine de Saint-Exupery

**Comment by jefffhaynes** [comment] 2015-01-05 02:24
I've added documentation to the new release.  Take a look when you get a chance.

https://github.com/jefffhaynes/BinarySerializer/tree/generated

Thanks

**Comment by xplicit** [comment] 2015-01-05 03:23
Thank you, this looks pretty good. I would add some short sample of serialization and deserialization at the beginning for quick start of using serializer.

And some comments about locking and caching.  There is a sample of code.

        //declaration
        private readonly Dictionary<Type, RootNode> _graphCache = new Dictionary<Type, RootNode>();


        //using    
            lock (_graphCacheLock)
            {
                RootNode graph = GetGraph(value.GetType());

                graph.SerializationContext = context;
                graph.Value = value;
                graph.Bind();

                graph.Serialize(stream);
            }

if `__graphCache` is not static, you don't need to lock before accessing it, because it's available only at the thread when BinarySerialized object is created. If someone want to access BinarySerializer object from another thread it should take care about locking ownself.  

But it would be much better if __graphCache is static. In this case you don't need to hold BinarySerializer object in memory for consequent serializations. You can create BinarySerializer when you need and metadata cache will be saved between this creatations. In this case you have to lock dictionary, before accessing it. 

But you don't have to lock all Serialization process. If you split metadata info of the type which is not changed due the program run from the context-depended data you'll be able to lock Dictionary only for adding or retrieving data to it.  

            RootNode graph;
            lock (_graphCacheLock)
            {
                graph = GetGraph(value.GetType());
            }
           
           //Serialization context-dependent object
           var contextGraph = new ContextGraph(graph);
           contextGraph.SerializationContext = context;
           contextGraph.Value = value;
           contextGraph.Bind();

           contextGraph.Serialize(stream);
           
Moreover is this case lock of __graphCacheLock will be inside of GetGraph method, where it'll be used when accessing the dictionary.

**Comment by jefffhaynes** [comment] 2015-01-05 05:25
Yes, that was my original intention. However, I was unable to make the graph completely immutable; therefore making it static would cause corruption when used across multiple threads. I do agree that I should remove the locks though, they don't make sense at this point. 

If you have any suggestions for ways to make the graph immutable, I would be interested in hearing it. Unfortunately, I think it's a difficult problem. The issue is the "Value" assignment, which should be thread-local. However, as it is you can only have one value per graph, effectively tying the graph to a specific thread. I'm sure there is a way to fix it, but I'm not sure how to go about it.  Look at the Value and BoundValue properties to see what I'm talking about.

**Comment by xplicit** [comment] 2015-01-05 07:29
Do I correctly understand that the Value property holds an object instance? I mean this 

     SomeType x=new SomeType();

and `Node.Value` contains x instance. If I undestand it correctly that the thing I talking about: split the Node behaviour into two classes. One (Node) will hold only type metadata information without object instances, other (e. g. ContextNode) will hold reference to metadata Node and object instance Value. There will be two graphs. One will hold Nodes with metadata info. Other will hold instance value. In this case BinarySerializer won't change __graphCache nodes at each serialization, because Node does not hold instances of the objects, only metadata info.

    private static readonly Dictionary<Type, RootNode> _graphCache = new Dictionary<Type, RootNode>();

**Comment by jefffhaynes** [comment] 2015-01-05 12:00
Yes, that's correct. However, there are inter-dependencies between the two
graphs that may be difficult to resolve. Most of the complexity arises from
the subtype support and generic collections, both of which are somewhat
atypical in their type structure (compared to plain old objects).  That
being said, I agree this is probably the right approach.




On Jan 5, 2015, at 2:29 AM, Sergey Zhukov <notifications@github.com> wrote:

Do I correctly understand that the Value property holds an object instance?
I mean this

 SomeType x=new SomeType();

and Node.Value contains x instance. If I undestand it correctly that the
thing I talking about: split the Node behaviour into two classes. One
(Node) will hold only type metadata information without object instances,
other (e. g. ContextNode) will hold reference to metadata Node and object
instance Value. There will be two graphs. One will hold Nodes with metadata
info. Other will hold instance value. In this case BinarySerializer won't
change __graphCache nodes at each serialization, because Node does not hold
instances of the objects, only metadata info.

private static readonly Dictionary<Type, RootNode> _graphCache = new
Dictionary<Type, RootNode>();

—
Reply to this email directly or view it on GitHub
<https://github.com/jefffhaynes/BinarySerializer/issues/2#issuecomment-68676029>
.

**Comment by jefffhaynes** [comment] 2015-01-16 02:19
Ok, I split everything into two graphs (phew...).  The result is 3.0.0 on nuget.  Pls take a look and if everything looks ok consider closing this :).  Thanks!

**Comment by xplicit** [comment] 2015-01-16 08:30
It works (at least in my signle-threaded benchmarks it works)

Some comments: 
https://github.com/jefffhaynes/BinarySerializer/blob/generated2graph/BinarySerializer/BinarySerializer.cs#L50
 is not thread safe. You should place whole `foreach` inside the lock, or make something like that:

     RootTypeNode[] nodes;
     lock  (graphCacheLock)
     {
        nodes = __graphCache.Values.ToArray();
     }
   
    foreach (RootTypeNode graph in nodes)
       graph.Endianess=value


https://github.com/jefffhaynes/BinarySerializer/blob/generated2graph/BinarySerializer/BinarySerializer.cs#L98-L99

This two lines are not thread-safe and should be removed.

If ` _graphCache` and `__graphCacheLock` were static the type would have been cached between the instances of the serializer.

**Comment by jefffhaynes** [comment] 2015-01-16 10:22
Yes, you're right. I think I just need to move the global endianness setting to the value graph instead of the type graph. Ah well, two steps forward...

**Comment by jefffhaynes** [comment] 2015-01-17 19:03
Ok, all set.  3.2 on nuget.

On Fri, Jan 16, 2015 at 5:22 AM, Jeff Haynes <feedyurhed@gmail.com> wrote:

> Yes, you're right. I think I just need to move the global endianness
> setting to the value graph instead of the type graph. Ah well, two steps
> forward...
>
>
> On Jan 16, 2015, at 3:30 AM, Sergey Zhukov <notifications@github.com>
> wrote:
>
> It works (at least in my signle-threaded benchmarks it works)
>
> Some comments:
>
> https://github.com/jefffhaynes/BinarySerializer/blob/generated2graph/BinarySerializer/BinarySerializer.cs#L50
> is not thread safe. You should place whole foreach inside the lock, or
> make something like that:
>
>  RootTypeNode[] nodes;
>  lock  (graphCacheLock)
>  {
>     nodes = __graphCache.Values.ToArray();
>  }
>
> foreach (RootTypeNode graph in nodes)
>    graph.Endianess=value
>
>
> https://github.com/jefffhaynes/BinarySerializer/blob/generated2graph/BinarySerializer/BinarySerializer.cs#L98-L99
>
> This two lines are not thread-safe and should be removed.
>
> If _graphCache and __graphCacheLock were static the type would have been
> cached between the instances of the serializer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jefffhaynes/BinarySerializer/issues/2#issuecomment-70222315>
> .
>
>


-- 
If you want to build a ship, don't drum up people together to collect wood
and don't assign them tasks and work, but rather teach them to long for the
endless immensity of the sea.

Antoine de Saint-Exupery

**Closed** 2015-01-18 18:30 UTC
