### ISSUE TITLE
[Ignore] execute get of property, causing error. Suggested feature option to ignore get or get errors when only deserializing.

### ISSUE THREAD

**Issue by mikedavison** [jefffhaynes/BinarySerializer#81] opened 2018-01-01 00:34 UTC
If the [Igonre] attribute is defined I would expect the deserializer to completely ignore the property, however running debug it still tries to execute the 'get' even though it does not try to deserialize. The problem is that if the property relies on some thing being initialized after deserialisation then the property throws an exception which stops the deserialization.

Is the BinarySerializer working 'as designed' or is there a bug?

Additional infomration
I have a property defined as (example code) ...
[Ignore] public int getSomething{
       get {
         return parent.getSomething();
      }
}
Note in this example code the problem is that the 'parent' is only set after deserialization.

**Comment by jefffhaynes** [comment] 2018-01-01 00:52
It’s working as intended because while it won’t serialize that property, it will include it in the graph in case you try to bind to it or, more importantly, a child of it. However, it seems reasonable to ignore exceptions in that case. Maybe rewrite the title slightly and I’ll take a look. Thanks.

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by jefffhaynes** [comment] 2018-01-01 14:02
Fixed in #83

**Closed by jefffhaynes** 2018-01-01 14:02 UTC
