### ISSUE TITLE
[FieldLength] for null string

### ISSUE THREAD

**Issue by abrasat** [jefffhaynes/BinarySerializer#5] opened 2015-03-06 16:56 UTC
It seems that the reserved field length for a string is ignored if the string is null. If the string is empty, it works fine.

[FieldLength(50)]
[SerializeAs(Encoding = "ASCII")]
public string Data { get; set; }

**Comment by jefffhaynes** [comment] 2015-03-06 19:29
Yeah, this is an interesting corner case.  I think it's working "as designed" but I can see that for fixed-length fields this would be confusing.  Let me think about it a little but I am concerned that if these fields aren't nullable it could cause other problems.  For example, if you have a trailing optional fixed-length string in a class this change would make it impossible to remove the field at runtime.  Put another way, a null string would no longer have meaning.

**Comment by jefffhaynes** [comment] 2015-03-08 22:49
Ok, the more I think about the more I think you're right. If there is a field length specified, that should take priority to null. I'll work on it and publish an update.

**Comment by abrasat** [comment] 2015-03-09 08:29
Thank you for the feedback.
I have a "collateral" question regarding the [FieldLength]. One of our classes that need to be binary serialized contains a list/array of elements (the type of an element is also a class), with a fixed "n" (maximum) size. That means that even if the list/array contains only lets say 3 elements, we still have to foresee a placeholder for "n" elements in the binary output. What would be the recommended annotation in this case ?

**Comment by jefffhaynes** [comment] 2015-03-09 23:33
Check out the documentation for FieldCount.  For three elements you can simply say [FieldCount(3)].

**Comment by jefffhaynes** [comment] 2015-03-09 23:34
Sorry, your example was for n elements, but you get the gist.

**Comment by abrasat** [comment] 2015-03-10 09:42
Ok, thanks.
I am just trying to figure out the handling of pascal strings (the first byte contains the string length) with the BinarySerializer. I saw the sample about the binding support in BinarySerializer, but I am still not sure how to solve it. In the byte-array there is a fixed amount of bytes allocated for the pascal string (lest say 51), and the first byte contains the "real" length (lets say 5). How can the 5 bytes containing the "netto" string information be extracted to a c# string, and still have 51 bytes as place holder ?

**Comment by abrasat** [comment] 2015-03-10 10:41
I tried also to use SerializedType.LengthPrefixedString (all string length are less than 128 bytes, I suppose that in this case only first byte will be used for the length), but somehow it seems to work only for the first string, the second one cannot be "decrypted" (is null). Is SerializedType.LengthPrefixedString supposed to work together with FieldLength ? If yes, should the FieldLength include the prefix byte containing the string length ?

**Comment by jefffhaynes** [comment] 2015-03-10 11:10
In the case of a field or member adorned with a FieldLength attribute, the serialized field will only contain the number of bytes specified by the attribute. If you specify FieldLength(6), the result will have exactly six bytes, irrespective of the actual string length. If the string is less than six bytes it will be padded by zeros. The same is true in the case of bound FieldLength attributes but the length is resolved at runtime. 

As for the LengthPrefixedString, a FieldLength wouldn't make sense as you would effectively be including the length in two places and the serializer doesn't know which one to use. I'm not sure what exactly the behavior is you're seeing with two prefixed strings but if you can post your code I'll take a look. Thanks.

**Comment by abrasat** [comment] 2015-03-10 11:21
The strings are not concatenated, the global message length should be constant. Thats why for instance 11 bytes (1 byte string length and 10 bytes string content) are allocated for each string.

The binary message contains several pascal strings, something like this:

0x3    <- first string length
0x41
0x42
0x44
0x0 <- padding byte
0x0 <- padding byte
0x0 <- padding byte
0x0 <- padding byte
0x0 <- padding byte
0x0 <- padding byte
0x0 <- padding byte
0x4   <- second string length
0x53
0x52
0x54
0x51
0x0 <- padding byte
0x0 <- padding byte
0x0 <- padding byte
0x0 <- padding byte
0x0 <- padding byte
0x0 <- padding byte
-> third string length and so on

Which annotation should be used for BinarySerialization in this case ?

**Comment by jefffhaynes** [comment] 2015-03-10 11:33
Interesting.  Unfortunately, I can't think of a straightforward way to do this with defining a custom class that implements IBinarySerializable.  It's a strange definition for a format or protocol as there seems to be some ambiguity as to the string length.  For example, if you had:

0x4 <- first string length
0x41
0x42
0x44
0x0 <- padding byte
0x0 <- padding byte
0x0 <- padding byte
0x0 <- padding byte
0x0 <- padding byte
0x0 <- padding byte
0x0 <- padding byte

What is the correct string length?  The field claims four, but the fourth position is null, yielding a string length of three.

Maybe this is something the serializer should handle but it isn't immediately obvious to me how it would work without introducing ambiguity.

**Comment by abrasat** [comment] 2015-03-10 11:39
The string length is 3 (0x4 is a typo), but still need an offset to the position where the next string starts.

**Comment by jefffhaynes** [comment] 2015-03-10 11:48
No, I modified your example to intentionally include a "typo" but my point was that the format allows for a certain amount of ambiguity (not necessarily a desirable thing is a format).  Is this something you're writing or an existing thing that you have to support?  If it's something new, you can simply write:

```c#
public class Entry
{
    public byte NameLength;

    [FieldLength("NameLength")]
    public int Name;
}
```

which would yield:

0x3 <- first string length
0x41
0x42
0x44

and then you could create a list or array of entries for multiple strings.

Actually, it occurs to me that it might be desirable to be able to write:

```c#
[FieldLength(11)]
public Entry Entry;
```

or

```c#
[ItemLength(11)]
public List<Entry> Entries;
```

and have each one correctly padded out, but I don't think that will work currently.  I'll take a look and see if it could be supported.

**Comment by abrasat** [comment] 2015-03-10 11:52
I am not writing a new protocol, it is the protocol used to communicate with an existing delphi application, which sends the strings in pascal format, with the first byte containing the "real" string length. And the strings are padded with 0x0 bytes, if actual string length is shorter than a max.length.

**Comment by jefffhaynes** [comment] 2015-03-10 11:55
Ok, I will look at implementing the fix tonight. Thanks.

**Comment by abrasat** [comment] 2015-03-10 15:05
Thank you.
Is it possible to use the FieldLength also for the max.size of a List of a class ?I have problems deserializing something like this:

...
    public class SuperClass
    {
        [FieldOrder(0)]
        [FieldLength(MaxNr_Class1)]
        public List<Class1> Class1List { get; set; }

        [FieldOrder(1)]
        [FieldLength(MaxNr_Class2)]
        public List<Class2> Class2List { get; set; }

        [FieldOrder(2)]
        [FieldLength(MaxNr_Class3)]
        public List<Class3> Class3List { get; set; }
    }

    public class Class1
    {
        [FieldOrder(0)]
        public Int32 ID { get; set; }

        [FieldOrder(1)]
        [FieldLength(MaxStrLen)]
        [SerializeAs(Encoding = "ASCII")]
        public string Name { get; set; }

        [FieldOrder(2)]
        [FieldLength(MaxStrLen)]
        [SerializeAs(Encoding = "ASCII")]
        public string Value { get; set; }
    }

    public class Class2
    {
        [FieldOrder(0)]
        public Int32 ID { get; set; }

        [FieldOrder(1)]
        [FieldLength(MaxStrLen)]
        [SerializeAs(Encoding = "ASCII")]
        public string Name { get; set; }

        [FieldOrder(2)]
        [FieldLength(MaxStrLen)]
        [SerializeAs(Encoding = "ASCII")]
        public string Value1 { get; set; }

        [FieldOrder(3)]
        [FieldLength(MaxStrLen)]
        [SerializeAs(Encoding = "ASCII")]
        public string Value2 { get; set; }
    }

    public class Class3
    {
        [FieldOrder(0)]
        public Int32 ID { get; set; }

        [FieldOrder(1)]
        [FieldLength(MaxStrLen)]
        [SerializeAs(Encoding = "ASCII")]
        public string Name { get; set; }

        [FieldOrder(2)]
        [FieldLength(MaxStrLen)]
        [SerializeAs(Encoding = "ASCII")]
        public string Value1 { get; set; }

        [FieldOrder(3)]
        [FieldLength(MaxStrLen)]
        [SerializeAs(Encoding = "ASCII")]
        public string Value2 { get; set; }

        [FieldOrder(4)]
        [FieldLength(MaxStrLen)]
        [SerializeAs(Encoding = "ASCII")]
        public string Value3 { get; set; }
    }

**Comment by jefffhaynes** [comment] 2015-03-10 19:16
Hm, that should work.  The setter being called twice is normal as the serializer is doing multiple passes in order to resolve bindings.  When I get a chance I'll try running your example although I might need your data to know for sure.

**Comment by jefffhaynes** [comment] 2015-03-11 03:29
Those changes turned out to uncover a number of issues with serialization and constrained objects.  I think I have everything ironed out but I want to do a little more testing and then I'll post the new version.  Thanks.

**Comment by abrasat** [comment] 2015-03-11 07:45
Thanks. Take your time for the testing, as I will not be able to continue my application testing till the end of the week.
What I think that would be a nice feature, especially when deserializing huge amounts of binary data into c# classes, is a kind of "verbose mode" property in the BinarySerializer. This would allow to track (if activated) the deserialization process, with information about the actually deserialized node name, list/array index and so on. Othewise it is quite difficult by just using the VisualStudio debugger to identify the different deserialization problems that might occur.

**Comment by jefffhaynes** [comment] 2015-03-11 14:27
You can get detailed information by hooking up to the various events provided by the serializer.  I'll amend the documentation to address that.  Thanks.

**Comment by jefffhaynes** [comment] 2015-03-12 03:24
Ok, I just published 3.8 and I believe all the changes you asked for are in there, including the null string fix.  Take a look and see if it works for you.  If you have any new issues, please open a new issue on here :).  Thanks!

**Comment by jefffhaynes** [comment] 2015-03-15 17:02
Let me know if you need more help with this.

**Comment by abrasat** [comment] 2015-03-16 07:23
Thanks for the update, I will start testing it today.
Regarding the serializer/deserializer debug events, would it be possible to get additionally for each node also the actual offset (position) in the stream ?

**Comment by abrasat** [comment] 2015-03-16 09:18
A first test shows that these 2 combinations still behave differently (some pascal strings are "cut" if using the "List" version)

public class SuperClass
{
    [FieldOrder(0)]
    [FieldLength(1)]
    public List<Class1> Class1List { get; set; }
}

This version still works ok:

public class SuperClass
{
    [FieldOrder(0)]
    public Class1 Class1Elem1 { get; set; }          
}

For me it is not clear why the BinarySerializer behaves differently regarding the deserialization of Class1, in the 2 examples above. The deserialization of Class1 should not behave differently if the Class1 instance is an element of a list or a single element.

**Comment by jefffhaynes** [comment] 2015-03-16 12:55
I'm not sure I'm entirely following. FieldLength(1) on a list will limit the length of the list to one byte. If you're trying to limit the list to one element you want FieldCount(1).

**Comment by abrasat** [comment] 2015-03-16 14:32
Thank you for the reply.
You are right, that was one of the problems.
The second problem was related to the encoding of the strings, I had to change it from ASCII to UTF-8 (had some characters above 128).

Did you changed anything regarding the "LengthPrefixedString" and "FieldLength" combination ?

**Comment by jefffhaynes** [comment] 2015-03-16 14:56
No, for the time being try using explicit field binding for string length.
The problem with LengthPrefixedString (and the reason I sort of wish it
didn't exist) is that the overall length is non-determinate.  If I need to
truncate the string, that will affect the length of the string, which may
affect the length of the length-specifier, which may affect the length of
the entire field, which may affect the length of the string, and so on.
I'm not sure how to resolve this so for the time-being I kind of ignored it.

On Mon, Mar 16, 2015 at 10:32 AM, abrasat <notifications@github.com> wrote:

> Thank you for the reply.
> You are right, that was one of the problems.
> The second problem was related to the encoding of the strings, I had to
> change it from ASCII to UTF-8 (had some characters above 128).
>
> Did you changed anything regarding the "LengthPrefixedString" and
> "FieldLength" combination ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jefffhaynes/BinarySerializer/issues/5#issuecomment-81702991>
> .
>



-- 
If you want to build a ship, don't drum up people together to collect wood
and don't assign them tasks and work, but rather teach them to long for the
endless immensity of the sea.

Antoine de Saint-Exupery

**Comment by abrasat** [comment] 2015-03-16 16:33
You are right, but you have anyway such "validation" issues during deserialization, due to eventually invalid configuration of the annotations in the c# class.. Similar problems occur if for instance a "wrongly" set FieldLength makes the deserializer to try to access bytes outside the binary stream length, this will also lead to some exception.
In my opinion it is usual that binary data have padding bytes. Very oft embedded systems are able only to send message with a fixed length, a "manual" concatenation of strings to avoid "empty" bytes would be a very "complicated" task to be solve inside such systems.
I have right-now a workaround by adding some code in the property "setter" and "getter" of each string, by "removing" the prefix-byte from the string in the "setter" and by adding it in the "getter". But such functionality should actually be integrated in the handling of "LengthPrefixedString" in the BinarySerializer implementation.

What I still dont understand is why the setters of the already deserialized list elements have to be called again when deserializing the next list elements (that means that if the list has 20 elements, the property setters of the first element are called 20 times during the deserialization of the list).

**Comment by jefffhaynes** [comment] 2015-03-16 17:13
Is there a way you can post your code somewhere so I can take a look at
it?  I'm still not sure I'm correctly picturing what you're describing.
Thanks.

On Mon, Mar 16, 2015 at 12:33 PM, abrasat <notifications@github.com> wrote:

> You are right, but you have anyway such "validation" issues during
> deserialization, due to eventually invalid configuration of the annotations
> in the c# class.. Similar problems occur if for instance a "wrongly" set
> FieldLength makes the deserializer to try to access bytes outside the
> binary stream length, this will also lead to some exception.
> In my opinion it is usual that binary data have padding bytes. Very oft
> embedded systems are able only to send message with a fixed length, a
> "manual" concatenation of strings to avoid "empty" bytes would be a very
> "complicated" task to be solve inside such systems.
> I have right-now a workaround by adding some code in the property "setter"
> and "getter" of each string, by "removing" the prefix-byte from the string
> in the "setter" and by adding it in the "getter". But such functionality
> should actually be integrated in the handling of "LengthPrefixedString" in
> the BinarySerializer implementation.
>
> What I still dont understand is why the setters of the already
> deserialized list elements have to be called again when deserializing the
> next list elements (that means that if the list has 20 elements, the
> property setters of the first element are called 20 times during the
> deserialization of the list).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jefffhaynes/BinarySerializer/issues/5#issuecomment-81779622>
> .
>



-- 
If you want to build a ship, don't drum up people together to collect wood
and don't assign them tasks and work, but rather teach them to long for the
endless immensity of the sea.

Antoine de Saint-Exupery

**Comment by abrasat** [comment] 2015-03-16 18:53
Binary Data structure :

byte 0 : element 1, string 1 length (=3)
byte 1 : char
byte 2 : char
byte 3 : char
byte 4 : 0
byte 5 : 0
...
byte 19 : 0
byte 20 : element 1, string 2 length (= 5)
byte 21 : char
byte 22 : char
byte 23 : char
byte 24 : char
byte 25 : char
byte 26 : 0
byte 27 : 0
...
byte 39 : 0
byte 40 : element 1, string 3 length (= 2)
byte 41 : char
byte 42 : char
byte 43 : 0
byte 44 : 0
...
byte 59 : 0
byte 60 : 0 (padding bytes - 0 -> placeholder for element 1, string 4)
byte 61 : 0
byte 62 : 0
byte 63 : 0
byte 64 : 0
...
byte 79 : 0
byte 80 : 0 (padding bytes - 0 -> placeholder for element 1, string 5)
byte 81 : 0
byte 82 : 0
byte 83 : 0
byte 84 : 0

...
byte 99 : 0
byte 100 : element 2, string 1 length (=4)
byte 101 : char
byte 102 : char
byte 103 : char
byte 104 : char
byte 105 : 0
...
byte 119 : 0
byte 120 : element 2, string 2 length (= 2)
byte 121 : char
byte 122 : char
byte 123 : 0
byte 124 : 0
...
byte 139 : 0
byte 140 : element 2, string 3 length (= 1)
byte 141 : char
byte 142 : 0
byte 143 : 0
byte 144 : 0
...
byte 159 : 0
byte 160 : element 2, string 4 length (= 3)
byte 161 : char
byte 162 : char
byte 163 : char
byte 164 : 0
...
byte 179 : 0
byte 180 : 0 (padding bytes - 0 -> placeholder for element 2, string 5)
byte 181 : 0
byte 182 : 0
byte 183 : 0
byte 184 : 0
...
byte 199 : 0
byte 200 : element 3, string 1 length (=2)
byte 201 : char
byte 202 : char
byte 203 : 0
...
byte 299 : 0
byte 300 : element 4, string 1 length (=3)
byte 301 : char
byte 302 : char
byte 303 : char 
byte 304 : 0
...
byte 399 : 0
byte 400 : 0 (padding bytes for element 5)
byte 401 : 0
byte 402 : 0
...
byte 499 : 0
byte 500 : 0 (padding bytes for element 6)
byte 501 : 0
byte 502 : 0
...
byte 599 : 0

The c# classes (the strings from ElemntClass could have also different allocated field length, have not to be identical)

    public class BinaryData
    {
        [FieldOrder(0)]
        [FieldCount(6)]
        public List<ElementClass> elements { get; set; }
    }

    public class ElementClass
    {
        private string string1;
        [FieldOrder(0)]
        [FieldLength(20)]
        [SerializeAs(Encoding = "UTF-8")]
        public string String1
        {
             get
             {
                 return string1;
             }
             set
             {
                 string1 = ConvertPascalStringToString(value);
             }
        }

        private string string2;
        [FieldOrder(1)]
        [FieldLength(20)]
        [SerializeAs(Encoding = "UTF-8")]
        public string String2
        {
             get
             {
                 return string2;
             }
             set
             {
                 string2 = ConvertPascalStringToString(value);
             }
        }

        private string string3;
        [FieldOrder(2)]
        [FieldLength(20)]
        [SerializeAs(Encoding = "UTF-8")]
        public string String3
        {
             get
             {
                 return string3;
             }
             set
             {
                 string3 = ConvertPascalStringToString(value);
             }
        }

        private string string4;
        [FieldOrder(3)]
        [FieldLength(20)]
        [SerializeAs(Encoding = "UTF-8")]
        public string String4
        {
             get
             {
                 return string4;
             }
             set
             {
                 string4 = ConvertPascalStringToString(value);
             }
        }

        private string string5;
        [FieldOrder(4)]
        [FieldLength(20)]
        [SerializeAs(Encoding = "UTF-8")]
        public string String5
        {
             get
             {
                 return string5;
             }
             set
             {
                 string5 = ConvertPascalStringToString(value);
             }
        }
    }

        static string ConvertPascalStringToString(string value)
        {
            string tempStr = String.Empty;
            if (value != null)
            {
                try
                {
                    value.Trim();
                    int strLen = value.Length;
                    if (strLen > 0)
                    {
                        char lenCh = value[0];
                        byte len = Convert.ToByte(lenCh);
                        if (strLen > (int)len)
                        {
                            tempStr = value.Substring(1, len);
                        }
                    }
                }
                catch { }
            }
            return tempStr;
        }

The combination of annotations that I would expect to work with the BinarySerializer (as I said above, the FieldLength could also be different for each string from the class, but all the strings contain the real string length in the first byte):

    public class ElementClass
    {
        [FieldOrder(0)]
        [FieldLength(20)]
        [SerializeAs(SerializedType.LengthPrefixedString)]
        public string String1 { get; set; }  

        [FieldOrder(1)]
        [FieldLength(20)]
        [SerializeAs(SerializedType.LengthPrefixedString)]
        public string String2 { get; set; }  

        [FieldOrder(2)]
        [FieldLength(20)]
        [SerializeAs(SerializedType.LengthPrefixedString)]
        public string String3 { get; set; }  

        [FieldOrder(3)]
        [FieldLength(20)]
        [SerializeAs(SerializedType.LengthPrefixedString)]
        public string String4 { get; set; }  

        [FieldOrder(4)]
        [FieldLength(20)]
        [SerializeAs(SerializedType.LengthPrefixedString)]
        public string String5 { get; set; }  
     }

**Comment by jefffhaynes** [comment] 2015-03-16 21:58
Unfortunately, this can't work because you don't know that LengthPrefixedString is going to be one byte in length.  The length is (per the BinaryWriter spec) encoded as LEB128, which is variable length.  Therefore it is not trivial to pad out the string predictably.  I would suggest you use this approach:

Define an "Entry" class:

```C#
public class Entry
{
    [FieldOrder(0)]
    public byte Length { get; set; }

    [FieldOrder(1)]
    [FieldLength("Length")]
    public string Value { get; set; }
}
```

Then you can do:

```C#
public class ElementClass 
{
    [FieldOrder(0)]
    [FieldLength(20)]
    public Entry Entry1 { get; set; }  

    [FieldOrder(1)]
    [FieldLength(20)]
    public Entry Entry2 { get; set; }  

    // etc
}
```

**Comment by abrasat** [comment] 2015-03-17 06:54
Unfortunately this does not seem to work. Did you tested it ?
The Entry1 is ok, but not Entry2.
Does the FieldLength[20] for Entry1 mean that Entry2 should be always read with an offset of 20 bytes from the stream start, regardless of the real string length in Entry1, or not ?

**Comment by jefffhaynes** [comment] 2015-03-17 10:58
No, sorry I didn't have time to test it. I'll look at it today. But yes, entry2 should always be offset by 20 bytes.  I will look at adding the stream offset as well.

**Comment by jefffhaynes** [comment] 2015-03-17 11:16
It turns out I tested serialization but not deserialization for this case and there was a bug.  Sorry about that.  Please try the new version.

**Comment by abrasat** [comment] 2015-03-17 15:30
Thank you for the update. It looks goods by now, the offset at deserialization is correct.
Does the version 3.8.3 already expose the stream offset in the debugging events (did not found it) ?

**Comment by jefffhaynes** [comment] 2015-03-17 15:35
No, showing offsets is going to take some doing as multiple nested streams are created during serialization/deserialization.  I'm going to close this and open a new issue with that.  Thanks.

**Closed by jefffhaynes** 2015-03-17 15:35 UTC

**Comment by jefffhaynes** [comment] 2015-03-22 17:25
I realized you won't get updates in the other issue but I just pushed 3.8.4, which has offsets in the events.  Enjoy!
