### ISSUE TITLE
Problem with deserialization on iOS

### ISSUE THREAD

**Issue by maddentist** [jefffhaynes/BinarySerializer#105] opened 2018-04-11 13:16 UTC
Attempting to deserialize the following object using Xamarin.iOS results in an error :

`public class PositionUpdatePackage
	{
		/// <summary>
		/// Device serial number
		/// </summary>
		[FieldOrder(0)]
		public uint DeviceUniqueIdentifier { get; set; }

		/// <summary>
		/// Device latitude
		/// </summary>
		[FieldOrder(1)]
		public double Latitude { get; set; }

		/// <summary>
		/// Device longitude
		/// </summary>
		[FieldOrder(2)]
		public double Longitude { get; set; }

		/// <summary>
		/// Device speed in meters per seconds
		/// </summary>
		[FieldOrder(3)]
		public short SpeedInMetersPerSecond { get; set; }

		/// <summary>
		/// Device heading in degrees (true)
		/// </summary>
		[FieldOrder(4)]
		public short Heading { get; set; }

		/// <summary>
		/// Device altitude in meters
		/// </summary>
		[FieldOrder(5)]
		public short AltitudeInMeter { get; set; }

		/// <summary>
		/// Device GNSS receiver horizontal precision in meters
		/// </summary>
		[FieldOrder(6)]
		public byte HorizontalAccuracyInMeters { get; set; }

		/// <summary>
		/// Device GNSS receiver vertical precision in meters
		/// </summary>
		[FieldOrder(7)]
		public byte VerticalAccuracyInMeters { get; set; }

		/// <summary>
		/// integer expression of device DeviceTypes value
		/// </summary>
		[FieldOrder(8)]
		public short DeviceType { get; set; }

		/// <summary>
		/// Presure in hPa has measured by device
		/// </summary>
		[FieldOrder(9)]
		public short Pressure { get; set; }

		/// <summary>
		/// Pressure altitude calculated by device
		/// </summary>
		[FieldOrder(10)]
		public short PressureAltitude { get; set; }

		/// <summary>
		/// Variometer provided by GPS device
		/// </summary>
		[FieldOrder(11)]
		public short Variometer { get; set; }

		/// <summary>
		/// Latitude and Longitude convertited to Position object
		/// </summary>
		[Ignore]
		public Position Position
		{
			get {
				return new Position(Latitude, Longitude, SpeedInMetersPerSecond, Heading, AltitudeInMeter, HorizontalAccuracyInMeters, VerticalAccuracyInMeters);
			}
		}
	}`

The error message is : **System.ExecutionEngineException: Attempting to JIT compile method '(wrapper delegate-invoke) <Module>:invoke_callvirt_void_PositionUpdatePackage_double (aero.airprox.global.net.Messaging.FromMessagingPackages.PositionUpdatePackage,double)' while running in aot-only mode. See https://developer.xamarin.com/guides/ios/advanced_topics/limitations/ for more information.**

**EDIT**
It works when the following class is deserialized:
`public class AutonomousRegistrationReturnPackage
	{
		/// <summary>
		/// Device Unique IDentifier attributed upon registration to be used for all further messages
		/// </summary>
		[FieldOrder(0)]
		public UInt32 DeviceUniqueIdentifier { get; set; }

		/// <summary>
		/// Device type expressed as int (cannot be null or equal to 0)
		/// </summary>
		[FieldOrder(1)]
		public Int16 DeviceType { get; set; }

		/// <summary>
		/// Minimum distance to send position changed message to cloud
		/// </summary>
		[FieldOrder(2)]
		public int MinimumDistanceInMeters { get; set; }

		/// <summary>
		/// Minimum timespan between position updates are sent to server
		/// </summary>
		[FieldOrder(3)]
		public int MinimumTimeInMilliseconds { get; set; }

		/// <summary>
		/// Dead man signal interval
		/// </summary>
		[FieldOrder(4)]
		public int DeadManSignalIntervalInMilliseconds { get; set; }

		/// <summary>
		/// Descirption (Friendly name, usually registration number) of device
		/// </summary>
		[FieldOrder(5)]
		public string Description { get; set; }

		/// <summary>
		/// Parameterless constructor used for serialization
		/// DO NOT USE
		/// </summary>
		public AutonomousRegistrationReturnPackage() { }

		/// <summary>
		/// Constructor for autonomous registration response message package
		/// </summary>
		/// <param name="fetchedIdentifier"></param>
		/// <param name="deviceType"></param>
		/// <param name="minimumDistance"></param>
		/// <param name="minimumTime"></param>
		/// <param name="deadMan"></param>
		/// <param name="desc"></param>
		public AutonomousRegistrationReturnPackage(UInt32 fetchedIdentifier, Int16 deviceType, int minimumDistance, int minimumTime, int deadMan, string desc)
		{
			DeviceUniqueIdentifier = fetchedIdentifier;
			DeviceType = deviceType;
			MinimumDistanceInMeters = minimumDistance;
			MinimumTimeInMilliseconds = minimumTime;
			DeadManSignalIntervalInMilliseconds = deadMan;
			Description = desc;
		}
	}`

I must admit that I'm a bit confused, both by the error message ans the expalnation given on the link. Please note that the above code works perfectly on .NET framework (runs on azure worker role), UWP and Xamarin.Android.

**Comment by jefffhaynes** [comment] 2018-04-12 01:17
Interesting.  I'm not sure what would cause that although there is some constructor generation that may qualify as JIT.  I'm traveling right now but when I get back I'll install Xamarin and try it out.

**Comment by maddentist** [comment] 2018-04-12 08:27
Thank you for your quick answer Jeff. As the link given states that it has something to do with lack of support for generic types in iOS. It might help you to know that the deserialization which causes the problem is wrapped in the following class :

`public async static Task<T> DeserializeToObjectAsync<T>(byte[] data)
{
            try
            {
                byte[] bytes = data.SubArray(1);

                BinarySerializer serializer = new BinarySerializer();
                using (MemoryStream compressed = new MemoryStream(bytes))
                {
                    if (data[0] != COMPRESSED)
                    {
                        return await serializer.DeserializeAsync<T>(compressed);
                    }
                    else
                    {
                        using (MemoryStream uncompressed = new MemoryStream())
                        {
                            using (GZipStream decompressor = new GZipStream(compressed, CompressionMode.Decompress))
                            {
                                decompressor.CopyTo(uncompressed);
                            }
                            uncompressed.Position = 0;
                            return await serializer.DeserializeAsync<T>(uncompressed);
                        }
                    }
                }
            }
            catch
            {
                return default(T);
            }
}`

**Comment by jefffhaynes** [comment] 2018-04-16 03:42
Out of curiosity, what makes you think it has something to do with generic type support versus the other limitations listed in the link?

**Comment by maddentist** [comment] 2018-04-18 12:34
> Out of curiosity, what makes you think it has something to do with generic type support versus the other limitations listed in the link?

I'm not really certain :-) 

Anyway, to add up to the mistery, it seems that the problem happens when the class the byte array is to be serialized into contains a double (or Double). I've tried with different classes that my project uses and lots of them are serialized/deserialized without a hiccup. I'll explore this further if this is of any help.

**Comment by jefffhaynes** [comment] 2018-04-18 13:11
I have some theories. I just don’t have a Mac to test them. Still working on it though...

________________________________

**Comment by maddentist** [comment] 2018-05-04 10:34
Any progress on that strange mistery ? (And many thanks for your time)

**Comment by jefffhaynes** [comment] 2018-05-04 11:38
No, sorry. I’ve been under water with work. I’ll try to get to it this weekend.

________________________________

**Comment by jefffhaynes** [comment] 2018-05-08 17:03
I don't have access to a mac and it's hard to guess what the issue is.  Can you checkout this repo and see if you can tell what line is throwing the exception?  I have some theories but no way to test them.

**Comment by maddentist** [comment] 2018-05-09 10:29
Thank you for your time ! I haven't had the opportunity to implement your code in my app (instead of getting it as a nuget package) to see precisely which line throws the exception. However, I removed some try catches and did some experiments. I now have a stacktrace which shows the signature of the offending methods which might help. I will investigate further if needed.


Stacktrace (Exception thrown while deserializing the aforementionned class : PositionUpdatePackage)


**Unhandled Exception:
System.ExecutionEngineException: Attempting to JIT compile method '(wrapper delegate-invoke) <Module>:invoke_callvirt_void_PositionUpdatePackage_double (aero.airprox.global.net.Messaging.FromMessagingPackages.PositionUpdatePackage,double)' while running in aot-only mode. See https://developer.xamarin.com/guides/ios/advanced_topics/limitations/ for more information.

  at (wrapper unknown) System.Object.gsharedvt_out()
  at BinarySerialization.MagicMethods+<>c__DisplayClass3_0`2[TTarget,TValue].<MagicActionHelper>g__Func|0 (System.Object target, System.Object value) [0x00003] in <4c2c902fcf84489690677de8253f47b4>:0 
  at BinarySerialization.Graph.ValueGraph.ObjectValueNode.GetValue (System.Func`2[T,TResult] childValueSelector) [0x00172] in <4c2c902fcf84489690677de8253f47b4>:0 
  at BinarySerialization.Graph.ValueGraph.ObjectValueNode.get_Value () [0x0000f] in <4c2c902fcf84489690677de8253f47b4>:0 
  at BinarySerialization.Gr
aph.ValueGraph.RootValueNode.get_Value () [0x0000b] in <4c2c902fcf84489690677de8253f47b4>:0 
  at BinarySerialization.BinarySerializer+<DeserializeAsync>d__31.MoveNext () [0x000ad] in <4c2c902fcf84489690677de8253f47b4>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Ver
sions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <c8e3aece7e434bb994fb57ae63a2f189>:0 
  at BinarySerialization.BinarySerializer+<DeserializeAsync>d__35`1[T].MoveNext () [0x00082] in <4c2c902fcf84489690677de8253f47b4>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152
 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <c8e3aece7e434bb994fb57ae63a2f189>:0 
  at aero.airprox.global.net.Helpers.B
inarySerializerWrapper+<DeserializeToObjectAsync>d__3`1[T].MoveNext () [0x000cb] in <1648abefbe2644dc8ff857d8fd69eb2c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices
/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <c8e3aece7e434bb994fb57ae63a2f189>:0 
  at aero.airprox.engine.bluetooth.BluetoothAirproxEngine+<PositionUpdateFromDeviceProcessing>d__10.MoveNext () [0x0006c] in <66ac2aa754d2468896837d99f90a452f>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1 (System.Object state
) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1034 
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x0000d] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1306 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:957 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in /Libra
ry/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:904 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1283 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:856 
  at ObjCRuntime.Runtime.ThreadPoolDispatcher (System.Func`1[TResult] callback) [0x00006] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:280 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00009] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/ms
corlib/system/threading/threadpool.cs:1208 
2018-05-09 12:23:44.628 aero.airprox.tallyho.bt.iOS[9900:4937514] Unhandled managed exception:
Attempting to JIT compile method '(wrapper delegate-invoke) <Module>:invoke_callvirt_void_PositionUpdatePackage_double (aero.airprox.global.net.Messaging.FromMessagingPackages.PositionUpdatePackage,double)' while running in aot-only mode. See https://developer.xamarin.com/guides/ios/advanced_topics/limitations/ for more information.
 (System.ExecutionEngineException)
  at (wrapper unknown) System.Object.gsharedvt_out()
  at BinarySerialization.MagicMethods+<>c__DisplayClass3_0`2[TTarget,TValue].<MagicActionHelper>g__Func|0 (System.Object target, System.Object value) [0x00003] in <4c2c902fcf84489690677de8253f47b4>:0 
  at BinarySerialization.Graph.ValueGraph.ObjectValueNode.GetValue (System.Func`2[T,TResult] childValueSelector) [0x00172] in <4c2c902fcf84489690677de8253f47b4>:0 
  at BinarySerialization.Graph.ValueGraph.ObjectValueNode.get_Value () [0x0000f] in <4c2c902fcf84489690677de8253f47b4>:0 
  at BinarySerializ
ation.Graph.ValueGraph.RootValueNode.get_Value () [0x0000b] in <4c2c902fcf84489690677de8253f47b4>:0 
  at BinarySerialization.BinarySerializer+<DeserializeAsync>d__31.MoveNext () [0x000ad] in <4c2c902fcf84489690677de8253f47b4>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.frame
work/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <c8e3aece7e434bb994fb57ae63a2f189>:0 
  at BinarySerialization.BinarySerializer+<DeserializeAsync>d__35`1[T].MoveNext () [0x00082] in <4c2c902fcf84489690677de8253f47b4>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommo
n.cs:152 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <c8e3aece7e434bb994fb57ae63a2f189>:0 
  at aero.airprox.global.net.H
elpers.BinarySerializerWrapper+<DeserializeToObjectAsync>d__3`1[T].MoveNext () [0x000cb] in <1648abefbe2644dc8ff857d8fd69eb2c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compiler
services/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <c8e3aece7e434bb994fb57ae63a2f189>:0 
  at aero.airprox.engine.bluetooth.BluetoothAirproxEngine+<PositionUpdateFromDeviceProcessing>d__10.MoveNext () [0x0006c] in <66ac2aa754d2468896837d99f90a452f>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1 (System.Obje
ct state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1034 
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x0000d] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1306 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:957 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] i
n /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:904 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1283 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:856 
  at ObjCRuntime.Runtime.ThreadPoolDispatcher (System.Func`1[TResult] callback) [0x00006] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:280 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00009] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/references
ource/mscorlib/system/threading/threadpool.cs:1208 
2018-05-09 12:23:44.629 aero.airprox.tallyho.bt.iOS[9900:4937514] critical: Stacktrace:

2018-05-09 12:23:44.629 aero.airprox.tallyho.bt.iOS[9900:4937514] critical: 
Native stacktrace:

2018-05-09 12:23:44.633 aero.airprox.tallyho.bt.iOS[9900:4937514] critical: 	0   aero.airprox.tallyho.bt.iOS         0x000000010457af14 aero.airprox.tallyho.bt.iOS + 60976916
2018-05-09 12:23:44.633 aero.airprox.tallyho.bt.iOS[9900:4937514] critical: 	1   libsystem_platform.dylib            0x0000000183c50b58 _sigtramp + 52
2018-05-09 12:23:44.634 aero.airprox.tallyho.bt.iOS[9900:4937514] critical: 	2   libsystem_pthread.dylib             0x0000000183c56288 <redacted> + 376
2018-05-09 12:23:44.634 aero.airprox.tallyho.bt.iOS[9900:4937514] critical: 	3   libsystem_c.dylib                   0x0000000183a23d0c abort + 140
2018-05-09 12:23:44.634 aero.airprox.tallyho.bt.iOS[9900:4937514] critical: 	4   aero.airprox.tallyho.bt.iOS         0x000000010468e6a8 xamarin_get_block_descriptor + 8528
2018-05-09 12:23:44.634 aero.airprox.tallyho.bt.iOS[9900:4937514] critical: 	5   aero.airprox.tallyho.bt.iOS         0x00000001045bae08 mono_pmip + 225712
2018-05-09 12:23:44.635 aero.airprox.tallyho.bt.iOS[9900:4937514] critical: 	6   aero.airprox.tallyho.bt.iOS         0x000000010461c784 mono_pmip + 625452
2018-05-09 12:23:44.635 aero.airprox.tallyho.bt.iOS[9900:4937514] critical: 	7   aero.airprox.tallyho.bt.iOS         0x000000010461776c mono_pmip + 604948
2018-05-09 12:23:44.636 aero.airprox.tallyho.bt.iOS[9900:4937514] critical: 	8   aero.airprox.tallyho.bt.iOS         0x00000001046160d0 mono_pmip + 599160
2018-05-09 12:23:44.636 aero.airprox.tallyho.bt.iOS[9900:4937514] critical: 	9   aero.airprox.tallyho.bt.iOS         0x000000010461cd78 mono_pmip + 626976
2018-05-09 12:23:44.636 aero.airprox.tallyho.bt.iOS[9900:4937514] critical: 	10  libsystem_pthread.dylib             0x0000000183c55220 <redacted> + 272
2018-05-09 12:23:44.637 aero.airprox.tallyho.bt.iOS[9900:4937514] critical: 	11  libsystem_pthread.dylib             0x0000000183c55110 <redacted> + 0
2018-05-09 12:23:44.637 aero.airprox.tallyho.bt.iOS[9900:4937514] critical: 	12  libsystem_pthread.dylib             0x0000000183c53b10 thread_start + 4
2018-05-09 12:23:44.637 aero.airprox.tallyho.bt.iOS[9900:4937514] critical: 
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================**

**Comment by jefffhaynes** [comment] 2018-05-09 13:35
That's what I was afraid of. The offending call is at the core of the serializer. It may simply turn out to be the case that iOS simply doesn't support the necessary methods. That being said, let me try to refactor that method for iOS and see if it makes a difference.

________________________________

**Comment by jefffhaynes** [comment] 2018-05-19 15:36
Can you tell me what version of XCode you were using for this?

**Comment by jefffhaynes** [comment] 2018-05-19 16:02
If you get a chance will you try 8.1.4-beta and see what happens?  Thanks

**Comment by jefffhaynes** [comment] 2018-06-02 16:22
Any chance you were able to look at this?

**Comment by maddentist** [comment] 2018-06-02 17:33
Unfortunately not yet but i'll try it ASAP

**Comment by jefffhaynes** [comment] 2018-06-02 18:59
No worries, I appreciate it

________________________________

**Comment by jefffhaynes** [comment] 2019-02-17 01:34
I don't have a great way to test this right now but it may be fixed in 8.2

**Closed by jefffhaynes** 2019-02-17 01:34 UTC
